angular.module("StockXApp",[])
         .controller("Ctrl",Ctrl);

         function Ctrl(){
             this.showImage=true;
             this.arrayIndex="";
             this.imagePath="";
             this.array=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25];
             this.showDiv=function(index){
                this.arrayIndex=index+1;
                this.showImage=!this.showImage;
                this.imagePath="./images/img'+this.arrayIndex+'.jpeg";
             }
             this.shoes = [
                {
                    "Brand":"A",
                    "Style":"a",
                    "Size":"1",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img1.jpeg"
                },{
                    "Brand":"B",
                    "Style":"b",
                    "Size":"2",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img2.jpeg"
                },{
                    "Brand":"C",
                    "Style":"c",
                    "Size":"3",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img3.jpeg"
                },{
                    "Brand":"D",
                    "Style":"d",
                    "Size":"4",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img4.jpeg"
                },{
                    "Brand":"E",
                    "Style":"e",
                    "Size":"5",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img5.jpeg"
                },{
                    "Brand":"F",
                    "Style":"f",
                    "Size":"6",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img6.jpeg"
                },{
                    "Brand":"G",
                    "Style":"g",
                    "Size":"7",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img7.jpeg"
                },{
                    "Brand":"H",
                    "Style":"h",
                    "Size":"8",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img8.jpeg"
                },{
                    "Brand":"I",
                    "Style":"i",
                    "Size":"9",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img9.jpeg"
                },{
                    "Brand":"J",
                    "Style":"j",
                    "Size":"10",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img10.jpeg"
                },{
                    "Brand":"K",
                    "Style":"k",
                    "Size":"11",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img11.jpeg"
                },{
                    "Brand":"L",
                    "Style":"l",
                    "Size":"12",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img12.jpeg"
                },{
                    "Brand":"M",
                    "Style":"m",
                    "Size":"13",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img13.jpeg"
                },{
                    "Brand":"N",
                    "Style":"n",
                    "Size":"14",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img14.jpeg"
                },{
                    "Brand":"O",
                    "Style":"o",
                    "Size":"15",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img15.jpeg"
                },{
                    "Brand":"P",
                    "Style":"p",
                    "Size":"16",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img16.jpeg"
                },{
                    "Brand":"Q",
                    "Style":"q",
                    "Size":"17",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img17.jpeg"
                },{
                    "Brand":"R",
                    "Style":"r",
                    "Size":"18",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img18.jpeg"
                },{
                    "Brand":"S",
                    "Style":"s",
                    "Size":"19",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img19.jpeg"
                },{
                    "Brand":"T",
                    "Style":"t",
                    "Size":"20",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img20.jpeg"
                },{
                    "Brand":"U",
                    "Style":"u",
                    "Size":"21",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img21.jpeg"
                },{
                    "Brand":"V",
                    "Style":"v",
                    "Size":"22",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img22.jpeg"
                },{
                    "Brand":"W",
                    "Style":"w",
                    "Size":"23",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img23.jpeg"
                },{
                    "Brand":"X",
                    "Style":"x",
                    "Size":"24",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img24.jpeg"
                },{
                    "Brand":"Y",
                    "Style":"y",
                    "Size":"25",
                    "UPC_ID":"#123",
                    "imagePath":"./images/img25.jpeg"
                }
                
                
                
                ];
         }